# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install -e ./parameterized-0.7.0
    pip install pytest
  workingDirectory: './backend'
  displayName: 'Install dependencies'

- script: pytest
  workingDirectory: './backend'
  displayName: 'Run testing with pytest'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'joachimveulemans/secure-messaging-system'
    command: 'build'
    Dockerfile: 'backend/Dockerfile'
    buildContext: 'backend'
    tags: 'backend'
