# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli
  workingDirectory: './frontend'
  displayName: 'npm install @angular/cli'

- script: npm install
  workingDirectory: './frontend'
  displayName: 'npm install dependencies'

- script: npm run build --prod
  workingDirectory: './frontend'
  displayName: 'npm run build --prod'

- script: npm run lint
  workingDirectory: './frontend'
  displayName: 'npm run lint'

- script: npm run test
  workingDirectory: './frontend'
  displayName: 'npm run test'

- script: npm audit
  workingDirectory: './frontend'
  displayName: 'npm audit'
